version: 2

models:
  - name: fact_transactions
    description: "Fact table consolidating transactions and linking to customer, product, and supplier dimensions."
    columns:
      - name: transaction_id
        description: "Unique identifier for each transaction."
      - name: product_id
        description: "Unique identifier for the product associated with the transaction."
      - name: product_name
        description: "Name of the product involved in the transaction."
      - name: product_category
        description: "Category of the product involved in the transaction."
      - name: product_price
        description: "Price of the product at the time of the transaction."
      - name: supplier_id
        description: "Unique identifier for the supplier providing the product."
      - name: supplier_name
        description: "Name of the supplier providing the product."
      - name: customer_id
        description: "Unique identifier for the customer involved in the transaction."
      - name: customer_name
        description: "Name of the customer involved in the transaction."
      - name: customer_email
        description: "Email of the customer involved in the transaction."
      - name: customer_phone
        description: "Phone number of the customer involved in the transaction."
      - name: customer_address
        description: "Address of the customer involved in the transaction."
      - name: transaction_date
        description: "Date when the transaction occurred."
      - name: transaction_total
        description: "Total monetary value of the transaction."
      - name: total_items
        description: "Total number of items in the transaction."

  - name: dim_customers
    description: "Dimension table containing customer information."
    columns:
      - name: customer_id
        description: "Unique identifier for each customer."
      - name: customer_name
        description: "Name of the customer."
      - name: customer_email
        description: "Email address of the customer."
      - name: customer_phone
        description: "Phone number of the customer."
      - name: customer_address
        description: "Address of the customer."
      - name: registration_date
        description: "Date the customer registered."

  - name: dim_products
    description: "Dimension table containing product information."
    columns:
      - name: product_id
        description: "Unique identifier for each product."
      - name: product_name
        description: "Name of the product."
      - name: product_category
        description: "Category of the product."
      - name: product_price
        description: "Price of the product."
      - name: stock
        description: "Available stock of the product."

  - name: dim_suppliers
    description: "Dimension table containing supplier information."
    columns:
      - name: supplier_id
        description: "Unique identifier for each supplier."
      - name: supplier_name
        description: "Name of the supplier."
      - name: supplier_email
        description: "Email address of the supplier."
      - name: supplier_phone
        description: "Phone number of the supplier."
      - name: supplier_address
        description: "Address of the supplier."
